[supportcoin]
 xrp = "x"
 xlm ="l"  #现在支持的币种

[system]
port = ":1234"

[dbDefault]
dbHost = "localhost"           #数据库连接地址
dbName = "phalgo"              #数据库名称
dbUser = "root"                #数据库用户名
dbPasswd = ""                  #数据库密码
dbPort = "3306"                #数据库端口号
dbOpenconns_max = 20           #最大连接数
dbIdleconns_max = 0            #最大空闲连接
dbType = "mysql"               #数据库类型